# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable_fri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('t_table', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('t_table', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_thu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('t_table', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_tue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('t_table', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_wed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('t_table', models.CharField(max_length=50)),
            ],
        ),
    ]
