# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_user_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_key',
            old_name='Key',
            new_name='key',
        ),
    ]
