# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20180503_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
    ]
